import streamlit as st
from app import load_css

st.set_page_config(page_title="Attack Simulation - SentinelAI", layout="wide")
load_css()

# ---------------------------------------------------------------
# Try to import the real scoring function from Person A's module.
# Falls back to a mock so the page still renders before integration.
# Delete the fallback once src/risk_engine.py exists and is confirmed working.
# ---------------------------------------------------------------
try:
    from src.scoring_service import score_event
    SCORING_LIVE = True
except Exception as e:
    SCORING_LIVE = False
    IMPORT_ERROR = f"{type(e).__name__}: {e}"

    def score_event(event):
        # Mock — matches the frozen contract shape only, not real logic.
        return {
            "rule_score": 70,
            "ml_score": 82,
            "final_score": 77,
            "risk_tier": "High",
            "reasons": ["Mock scoring — src/scoring_service.py import failed"],
            "recommended_action": "Require step-up MFA and temporarily restrict sensitive actions",
        }

# ---------------------------------------------------------------
# The four locked scenarios from the sprint plan (page 11).
# user_id values must exist in data/users.csv (format: PREFIX-NNN,
# e.g. DBA-001, SYS-002 — generated by src/generate_data.py).
# Resource choices are pulled from Person A's PERSONA_TEMPLATES
# in generate_data.py so sensitivity/approval logic lines up for real.
# resource_sensitivity values come from his RESOURCE_SENSITIVITY dict.
# ---------------------------------------------------------------
SCENARIOS = {
    "Compromised DBA": {
        "user_id": "DBA-001",
        "action": "suspicious_remote_login",
        "resource": "Identity Server",           # not in DBA's approved list
        "resource_sensitivity": 5,
        "login_hour": 2,                          # outside normal window
        "device_id": "UNKNOWN-DEVICE-001",
        "failed_attempts": 3,
        "data_downloaded_mb": 12,
        "privilege_change": False,
        "audit_log_disabled": False,
        "usual_device": False,
        "usual_resource": False,
        "approved_maintenance_window": False,
    },
    "Data Exfiltration": {
        "user_id": "DBA-002",
        "action": "bulk_customer_data_export",
        "resource": "KYC Database",               # approved for DBA
        "resource_sensitivity": 5,
        "login_hour": 14,                          # inside normal window
        "device_id": "DBA-002-DEV-01",             # a real approved device
        "failed_attempts": 0,
        "data_downloaded_mb": 6500,                # far above baseline mean
        "privilege_change": False,
        "audit_log_disabled": False,
        "usual_device": True,
        "usual_resource": True,
        "approved_maintenance_window": False,
    },
    "Privilege Abuse": {
        "user_id": "SYS-001",
        "action": "privilege_escalation_attempt",
        "resource": "Identity and Access Management",
        "resource_sensitivity": 5,
        "login_hour": 11,
        "device_id": "SYS-001-DEV-01",
        "failed_attempts": 5,                      # triggers repeated-failures rule
        "data_downloaded_mb": 4,
        "privilege_change": True,
        "audit_log_disabled": False,
        "usual_device": True,
        "usual_resource": False,                   # not in Sys Admin's approved list
        "approved_maintenance_window": False,
    },
    "Evidence Tampering": {
        "user_id": "SEC-001",
        "action": "disable_audit_logging",
        "resource": "Security Incident Repository",  # approved for Security Admin
        "resource_sensitivity": 4,
        "login_hour": 23,
        "device_id": "SEC-001-DEV-01",
        "failed_attempts": 1,
        "data_downloaded_mb": 30,
        "privilege_change": False,
        "audit_log_disabled": True,
        "usual_device": True,
        "usual_resource": True,
        "approved_maintenance_window": False,
    },
}

TIER_BADGE = {"Low": "badge-low", "Medium": "badge-medium", "High": "badge-high", "Critical": "badge-critical"}

st.title("Attack Simulation")
st.caption("Trigger a locked scenario to run it through the live scoring pipeline")

if not SCORING_LIVE:
    st.warning(f"Live scoring unavailable, showing mock results. Import error: {IMPORT_ERROR}")

if "sim_result" not in st.session_state:
    st.session_state.sim_result = None
    st.session_state.sim_name = None

cols = st.columns(4)
for col, name in zip(cols, SCENARIOS.keys()):
    if col.button(name, use_container_width=True):
        st.session_state.sim_result = score_event(SCENARIOS[name])
        st.session_state.sim_name = name

st.write("")

if st.session_state.sim_result:
    result = st.session_state.sim_result
    st.markdown(
        f'<div class="panel">'
        f'<p class="panel-title">Result — {st.session_state.sim_name}</p>',
        unsafe_allow_html=True,
    )

    score_cols = st.columns(4)
    score_cols[0].markdown(
        f'<p class="metric-label">Rule score</p><p class="metric-value">{result["rule_score"]}</p>',
        unsafe_allow_html=True,
    )
    score_cols[1].markdown(
        f'<p class="metric-label">ML score</p><p class="metric-value">{result["ml_score"]}</p>',
        unsafe_allow_html=True,
    )
    score_cols[2].markdown(
        f'<p class="metric-label">Final score</p><p class="metric-value">{result["final_score"]}</p>',
        unsafe_allow_html=True,
    )
    score_cols[3].markdown(
        f'<p class="metric-label">Risk tier</p>'
        f'<span class="badge {TIER_BADGE.get(result["risk_tier"], "badge-medium")}">{result["risk_tier"]}</span>',
        unsafe_allow_html=True,
    )

    st.write("")
    st.markdown(
        f'**Reasons:** {", ".join(result["reasons"]) if result["reasons"] else "None"}  \n'
        f'**Recommended action:** {result["recommended_action"]}'
    )
    st.markdown("</div>", unsafe_allow_html=True)
else:
    st.info("Select a scenario above to run it through score_event().")